name: 💻  New Hub - Information Provider
description: Provide information about creating a new hub for 2i2c to operate
title: "[Information Provider] New Hub: {{ HUB NAME }}"
labels: ["type: hub"]
body:
  - type: markdown
    attributes:
      value: |
        # Ask for a new 2i2c JupyterHub!

        This template is designed to help you provide information about your 2i2c Hub so that a 2i2c Engineer can set it up properly. Answer the sections below as best you can. We can update information as we learn more.

        # Community Information

  - type: textarea
    id: important-dates
    attributes:
      label: Important dates
      description: |
        Any important dates that we should consider for this hub. For example, if it will be used for a class, the starting day of class and any days with tests.
      value: |
        - **Target start date**: <!-- choose a target date ~1 week earlier than the required date -->
        - **Required start date**: <!-- the hub MUST by running as-needed by this date -->
        - **Any important dates for usage**: <!-- For example - exams, periods of heavy usage, etc. -->
    validations:
      required: true
  
