# Inspired from https://stefanbuck.com/blog/codeless-contributions-with-github-issue-forms
name: Comment on issues requesting deployment with pending information
on:
  issues:
    types:
       - labeled
jobs:
  ask-for-pending-information:
    if: github.event.label.name == 'new hub'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/2_new-hub-provide-info.yml
      - name: Find missing info in form
        shell: python
        id: find-missing-info
        run: |
          import os
          import sys

          # Setup variables
          form = ${{ steps.issue-parser.outputs.jsonString }}
          pending_info = {}
          for form_entry_id, form_entry_value in form.items():
            if not form_entry_value or form_entry_value == "pending":
                pending_info[form_entry_id] = form_entry_id.replace("_","")
                # print(form_entry_id.replace("_"," "))
          print(pending_info)
          if "GITHUB_OUTPUT" in os.environ :
            with open(os.environ["GITHUB_OUTPUT"], "a") as f :
                for key, value in pending_info.items() :
                  print("{0}={1}".format(key, value), file=f)
          else :
              for key, value in pending_info.items() :
                  print("::set-output name={0}::{1}".format(key, value))
      - run: echo '${{ steps.find-missing-info.outputs.jsonString }}'
