# Inspired from https://stefanbuck.com/blog/codeless-contributions-with-github-issue-forms
name: Comment on issues requesting deployment with pending information
on:
  issues:
    types:
       - labeled
jobs:
  ask-for-pending-information:
    if: github.event.label.name == 'new hub'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/2_new-hub-provide-info.yml
      - name: Save form info into a json
        run: echo '${{ steps.issue-parser.outputs.jsonString }}' > form.json
      - run: cat form.json
      - name: Find missing
        shell: python
        run: |
          import os
          import sys

          # Setup variables
          form = ${{ steps.issue-parser.outputs.jsonString }}
          print(form)
          for a in form:
            print(a)
