# .github/workflows/auto-author-assign.yml
name: Auto Author Assign

on:
  issues:
    types:
      - opened
      - reopened
      - labeled
permissions:
  issues: write

jobs:
  assign-author:
    if: contains(github.event.issue.labels.*.name, 'bug')
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.2
