name: Show best-practices
on: 
  issues:
    types: [labeled]

jobs:
  comment_on_impact_issues:
    if: |
      github.event.label.name == 'impact'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.6.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var msg = `Hey :wave: Do you want to find out more about what are the best practices when running your event using mybinder.org?`
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
